//! Generated gateway bootstrap for sdkwork-voice.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_web_bootstrap::ContractFallbackConfig;

pub struct ApplicationAssembly {
    pub router: Router,
    pub voice_pool: sdkwork_database_sqlx::DatabasePool,
}

pub async fn assemble_application_router() -> Result<ApplicationAssembly, String> {
    let assembly =
        sdkwork_voice_embedded_bootstrap::assemble_embedded_voice_application_router_from_env()
            .await?;
    Ok(ApplicationAssembly {
        router: assembly.router,
        voice_pool: assembly.voice_pool,
    })
}

pub fn gateway_contract_fallback_config() -> ContractFallbackConfig {
    let app_manifest = sdkwork_routes_voice_app_api::gateway_route_manifest();
    let backend_manifest = sdkwork_routes_voice_backend_api::gateway_route_manifest();

    let mut config = ContractFallbackConfig::from_manifest(&app_manifest);
    config.manifest_paths.extend(
        ContractFallbackConfig::from_manifest(&backend_manifest)
            .manifest_paths
            .into_iter(),
    );
    config
}
