//! Generated API assembly bootstrap for sdkwork-voice.
//! Regenerated by pnpm api:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;
use std::sync::Arc;

pub struct ApiAssembly {
    pub router: Router,
}

pub fn assemble_api_router() -> ApiAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_voice_app_api::gateway_mount(service));
    router = router.merge(sdkwork_routes_voice_backend_api::gateway_mount(service));
    ApiAssembly { router }
}
