//! Generated gateway bootstrap for sdkwork-voice.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_web_bootstrap::{
    ApiAssemblyContribution, ContractFallbackConfig, DatabasePoolReadinessCheck,
};
use sdkwork_web_core::HttpRouteManifest;
use std::sync::Arc;

pub struct ApiAssembly {
    pub router: Router,
    pub voice_pool: sdkwork_database_sqlx::DatabasePool,
}

pub async fn assemble_api_router() -> Result<ApiAssembly, String> {
    let assembly =
        sdkwork_voice_embedded_bootstrap::assemble_embedded_voice_application_router_from_env()
            .await?;
    Ok(ApiAssembly {
        router: assembly.router,
        voice_pool: assembly.voice_pool,
    })
}

/// Assemble the voice router against a caller-provided database pool so the
/// platform cloud gateway can share its process-wide PostgreSQL pool.
pub async fn assemble_api_router_with_pool(
    pool: sdkwork_database_sqlx::DatabasePool,
) -> Result<ApiAssembly, String> {
    let assembly =
        sdkwork_voice_embedded_bootstrap::assemble_embedded_voice_application_router(pool).await?;
    Ok(ApiAssembly {
        router: assembly.router,
        voice_pool: assembly.voice_pool,
    })
}

/// Build the complete host-neutral voice contribution for gateway embedding.
pub async fn assemble_contribution_with_pool(
    pool: sdkwork_database_sqlx::DatabasePool,
) -> Result<ApiAssemblyContribution, String> {
    let assembly = assemble_api_router_with_pool(pool).await?;
    let mut routes = Vec::new();
    routes.extend_from_slice(sdkwork_routes_voice_app_api::gateway_route_manifest().routes());
    routes.extend_from_slice(sdkwork_routes_voice_backend_api::gateway_route_manifest().routes());
    ApiAssemblyContribution::from_manifest(
        "sdkwork-voice",
        "SDKWork Voice API",
        assembly.router,
        HttpRouteManifest::from_owned_routes(routes),
        Vec::new(),
        Arc::new(DatabasePoolReadinessCheck::new(assembly.voice_pool)),
    )
}

pub fn gateway_contract_fallback_config() -> ContractFallbackConfig {
    let app_manifest = sdkwork_routes_voice_app_api::gateway_route_manifest();
    let backend_manifest = sdkwork_routes_voice_backend_api::gateway_route_manifest();

    let mut config = ContractFallbackConfig::from_manifest(&app_manifest);
    config.manifest_paths.extend(
        ContractFallbackConfig::from_manifest(&backend_manifest)
            .manifest_paths
            .into_iter(),
    );
    config
}
