import type {
  VoiceLocalApiCapability,
  VoiceLocalApiClientProtocol,
  VoiceLocalApiProxyHttpMethod,
} from "./types.ts";

export type VoiceLocalApiProxyRouteGroupId = "voice-audio";

export interface VoiceLocalApiProxyOperation {
  capability: VoiceLocalApiCapability;
  consumerProtocol: VoiceLocalApiClientProtocol;
  groupId: VoiceLocalApiProxyRouteGroupId;
  id: string;
  method: VoiceLocalApiProxyHttpMethod;
  pathPattern: string;
  probeSupport: boolean;
  streaming: boolean;
}

export interface VoiceLocalApiProxyRouteGroup {
  capabilityFamilies: VoiceLocalApiCapability[];
  id: VoiceLocalApiProxyRouteGroupId;
  operationIds: string[];
}

const VOICE_LOCAL_API_PROXY_OPERATION_CATALOG = [
  {
    id: "openai.v1.audio.speech.create",
    capability: "audio-speech",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/audio/speech",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.audio.transcriptions.create",
    capability: "audio-transcription",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/audio/transcriptions",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.audio.translations.create",
    capability: "audio-translation",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/audio/translations",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.audio.voices.list",
    capability: "audio-voice-catalog",
    consumerProtocol: "openai-compatible",
    method: "GET",
    pathPattern: "/v1/audio/voices",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.audio.voices.create",
    capability: "audio-voice-catalog",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/audio/voices",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.audio.voices.retrieve",
    capability: "audio-voice-catalog",
    consumerProtocol: "openai-compatible",
    method: "GET",
    pathPattern: "/v1/audio/voices/{voice_id}",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.audio.voice_consents.list",
    capability: "audio-voice-consent",
    consumerProtocol: "openai-compatible",
    method: "GET",
    pathPattern: "/v1/audio/voice_consents",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.audio.voice_consents.create",
    capability: "audio-voice-consent",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/audio/voice_consents",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.audio.voice_consents.retrieve",
    capability: "audio-voice-consent",
    consumerProtocol: "openai-compatible",
    method: "GET",
    pathPattern: "/v1/audio/voice_consents/{consent_id}",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.audio.voice_consents.update",
    capability: "audio-voice-consent",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/audio/voice_consents/{consent_id}",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.audio.voice_consents.delete",
    capability: "audio-voice-consent",
    consumerProtocol: "openai-compatible",
    method: "DELETE",
    pathPattern: "/v1/audio/voice_consents/{consent_id}",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.realtime.sessions.create",
    capability: "audio-realtime-session",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/realtime/sessions",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.realtime.client_secrets.create",
    capability: "audio-realtime-client-secret",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/realtime/client_secrets",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.realtime.calls.create",
    capability: "audio-realtime-call",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/realtime/calls",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.realtime.calls.accept.create",
    capability: "audio-realtime-call",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/realtime/calls/{call_id}/accept",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.realtime.calls.hangup.create",
    capability: "audio-realtime-call",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/realtime/calls/{call_id}/hangup",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.realtime.calls.refer.create",
    capability: "audio-realtime-call",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/realtime/calls/{call_id}/refer",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.realtime.calls.reject.create",
    capability: "audio-realtime-call",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/realtime/calls/{call_id}/reject",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.realtime.transcription_sessions.create",
    capability: "audio-realtime-transcription",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/realtime/transcription_sessions",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "openai.v1.realtime.translations.create",
    capability: "audio-realtime-translation",
    consumerProtocol: "openai-compatible",
    method: "POST",
    pathPattern: "/v1/realtime/translations",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "suno.v1.music.generations.create",
    capability: "audio-music",
    consumerProtocol: "custom-http",
    method: "POST",
    pathPattern: "/suno/v1/music/generations",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "suno.v1.music.generations.retrieve",
    capability: "audio-music",
    consumerProtocol: "custom-http",
    method: "GET",
    pathPattern: "/suno/v1/music/generations/{task_id}",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "elevenlabs.v1.sound_generation.create",
    capability: "audio-sound-effect",
    consumerProtocol: "custom-http",
    method: "POST",
    pathPattern: "/provider/elevenlabs/v1/sound-generation",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "volcengine.api.v3.contents.generations.tasks.create",
    capability: "audio-music",
    consumerProtocol: "custom-http",
    method: "POST",
    pathPattern: "/volcengine/api/v3/contents/generations/tasks",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "volcengine.api.v3.contents.generations.tasks.retrieve",
    capability: "audio-music",
    consumerProtocol: "custom-http",
    method: "GET",
    pathPattern: "/volcengine/api/v3/contents/generations/tasks/{task_id}",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "kling.v1.videos.generations.create",
    capability: "audio-generated-video",
    consumerProtocol: "custom-http",
    method: "POST",
    pathPattern: "/kling/v1/videos/generations",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "kling.v1.videos.generations.retrieve",
    capability: "audio-generated-video",
    consumerProtocol: "custom-http",
    method: "GET",
    pathPattern: "/kling/v1/videos/generations/{task_id}",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "nano-banana.v1.images.generations.create",
    capability: "audio-generated-image",
    consumerProtocol: "custom-http",
    method: "POST",
    pathPattern: "/nano-banana/v1/images/generations",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "nano-banana.v1.images.generations.retrieve",
    capability: "audio-generated-image",
    consumerProtocol: "custom-http",
    method: "GET",
    pathPattern: "/nano-banana/v1/images/generations/{task_id}",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "midjourney.v1.images.generations.create",
    capability: "audio-generated-image",
    consumerProtocol: "custom-http",
    method: "POST",
    pathPattern: "/midjourney/v1/images/generations",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "midjourney.v1.images.generations.retrieve",
    capability: "audio-generated-image",
    consumerProtocol: "custom-http",
    method: "GET",
    pathPattern: "/midjourney/v1/images/generations/{task_id}",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "vidu.ent.v2.reference2image.create",
    capability: "audio-generated-image",
    consumerProtocol: "custom-http",
    method: "POST",
    pathPattern: "/vidu/ent/v2/reference2image",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "vidu.ent.v2.text2video.create",
    capability: "audio-generated-video",
    consumerProtocol: "custom-http",
    method: "POST",
    pathPattern: "/vidu/ent/v2/text2video",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "vidu.ent.v2.img2video.create",
    capability: "audio-generated-video",
    consumerProtocol: "custom-http",
    method: "POST",
    pathPattern: "/vidu/ent/v2/img2video",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "vidu.ent.v2.reference2video.create",
    capability: "audio-generated-video",
    consumerProtocol: "custom-http",
    method: "POST",
    pathPattern: "/vidu/ent/v2/reference2video",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "vidu.ent.v2.start_end2video.create",
    capability: "audio-generated-video",
    consumerProtocol: "custom-http",
    method: "POST",
    pathPattern: "/vidu/ent/v2/start-end2video",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
  {
    id: "vidu.ent.v2.tasks.creations.list",
    capability: "audio-generated-video",
    consumerProtocol: "custom-http",
    method: "GET",
    pathPattern: "/vidu/ent/v2/tasks/{task_id}/creations",
    streaming: false,
    groupId: "voice-audio",
    probeSupport: true,
  },
] as const satisfies readonly VoiceLocalApiProxyOperation[];

const VOICE_LOCAL_API_PROXY_ROUTE_CAPABILITIES: readonly VoiceLocalApiCapability[] = [
  "audio-speech",
  "audio-transcription",
  "audio-translation",
  "audio-voice-catalog",
  "audio-voice-consent",
  "audio-sound-effect",
  "audio-music",
  "audio-generated-image",
  "audio-generated-video",
  "audio-realtime-session",
  "audio-realtime-client-secret",
  "audio-realtime-call",
  "audio-realtime-transcription",
  "audio-realtime-translation",
];

export function createVoiceLocalApiProxyOperationCatalog(): VoiceLocalApiProxyOperation[] {
  return VOICE_LOCAL_API_PROXY_OPERATION_CATALOG.map((operation) => ({ ...operation }));
}

export function findVoiceLocalApiProxyOperation(operationId: string) {
  return createVoiceLocalApiProxyOperationCatalog().find((operation) => operation.id === operationId);
}

export function listVoiceLocalApiProxyOperationsByCapability(capability: VoiceLocalApiCapability) {
  return createVoiceLocalApiProxyOperationCatalog().filter((operation) => operation.capability === capability);
}

export function createVoiceLocalApiProxyRouteGroups(
  operations = createVoiceLocalApiProxyOperationCatalog(),
): VoiceLocalApiProxyRouteGroup[] {
  const group: VoiceLocalApiProxyRouteGroup = {
    capabilityFamilies: [...VOICE_LOCAL_API_PROXY_ROUTE_CAPABILITIES],
    id: "voice-audio",
    operationIds: operations.filter((operation) => operation.groupId === "voice-audio").map((operation) => operation.id),
  };

  return group.operationIds.length > 0 ? [group] : [];
}
